### ISSUE TITLE
ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.

### ISSUE THREAD

**Issue by lha123456** [naver/sqlova#30]
Hi, I've tried to run train.py and getting this error, how should I do to solve it?
Traceback (most recent call last):
  File "train.py", line 607, in <module>
    dset_name='train')
  File "train.py", line 310, in train
    cnt_x1_list, g_ans, pr_ans = get_cnt_x_list(engine, tb, g_sc, g_sa, sql_i, pr_sc, pr_sa, pr_sql_i)
  File "/home/ubuntu/hengan.liao/sqlova-master/sqlova/utils/utils_wikisql.py", line 1652, in get_cnt_x_list
    g_ans1 = engine.execute(tb[b]['id'], g_sc[b], g_sa[b], g_sql_i[b]['conds'])
  File "/home/ubuntu/hengan.liao/sqlova-master/sqlnet/dbengine.py", line 29, in execute
    table_info = self.db.query('SELECT sql from sqlite_master WHERE tbl_name = :name', name=table_id).all()[0].sql.replace('\n','')
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/records.py", line 195, in all
    rows = list(self)
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/records.py", line 126, in __iter__
    yield next(self)
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/records.py", line 136, in __next__
    nextrow = next(self._rows)
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/records.py", line 365, in <genexpr>
    row_gen = (Record(cursor.keys(), row) for row in cursor)
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 946, in __iter__
    row = self.fetchone()
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1276, in fetchone
    e, None, None, self.cursor, self.context
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1268, in fetchone
    row = self._fetchone_impl()
  File "/home/ubuntu/anaconda3/envs/wcyEnv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1148, in _fetchone_impl
    return self.cursor.fetchone()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by whwang299** [comment]
Hi @lha123456 

Which version of `records` you are using? Could you try again with records=0.5.2 (https://github.com/naver/sqlova/issues/8)?

**Comment by lha123456** [comment]
@whwang299 I try again with records==0.5.2 and the issue has been solved, Thank you very much!
