### ISSUE TITLE
File Not found issue

### ISSUE THREAD

**Issue by alekdev2019** [naver/sqlova#5]
Hi 
I found your paper and github code and very interested in this topic.
I've tried to test your current result, but facing errors due to your files.
From [here](https://github.com/naver/sqlova#running-code), I tried to run the `python3 train.py --seed 1 --bS 16 --accumulate_gradients 2 --bert_type_abb uS --fine_tune --lr 0.001 --lr_bert 0.00001 --max_seq_leng 222`. 
But I got the error like:
`python train.py --seed 1 --bS 16 --accumulate_gradients 2 --bert_type_abb uS --fine_tune --lr 0.001 --lr_bert 0.00001 --max_seq_leng 222
BERT-type: uncased_L-12_H-768_A-12
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    train_data, train_table, dev_data, dev_table, train_loader, dev_loader = get_data(path_wikisql, args)
  File "train.py", line 183, in get_data
    train_data, train_table, dev_data, dev_table, _, _ = load_wikisql(path_wikisql, args.toy_model, args.toy_size, no_w2i=True, no_hs_tok=True)
  File "/home/ubuntu/work/torch-sqlova/sqlova/sqlova/utils/utils_wikisql.py", line 29, in load_wikisql
    train_data, train_table = load_wikisql_data(path_wikisql, mode='train', toy_model=toy_model, toy_size=toy_size, no_hs_tok=no_hs_tok, aug=aug)
  File "/home/ubuntu/work/torch-sqlova/sqlova/sqlova/utils/utils_wikisql.py", line 58, in load_wikisql_data
    with open(path_sql) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wonseok/data/wikisql_tok/train_tok.jsonl'`

I think you have additional data except of this repository code.
What is your additional data?
Thank you.

**Comment by whwang299** [comment]
Hi @alekdev2019 

Please refer to the issue #4 .

Thanks!

**Comment by alekdev2019** [comment]
Thank you for your quick solution.
I am interesting in changing your code with some different method.
For now, you've been using PyTorch to build the network, but I would like to change it with Tensorflow based.
Would you let me know what is the quick way to achieve this purpose?
Thank you

**Comment by whwang299** [comment]
Maybe you can start from original [BERT code](https://github.com/google-research/bert)?
Also, as far as I know, most of "natural language → SQL" models are written in pytorch except fews like [MAPO](https://github.com/crazydonkey200/neural-symbolic-machines) (but this is about weak-supervision model) and some [baseline code](https://github.com/jkkummerfeld/text2sql-data) for other SQL training set.

Sorry I can't be of more help on this issue. 

Wonseok

**Comment by alekdev2019** [comment]
Thank you for your help.

**Comment by alekdev2019** [comment]
I have an update on this spec.
I am willing to use Keras, and Keras include a lot of similar module with PyTorch.
I am very concerned how I need to convert a class based code(PyTorch)
import torch
import torch.nn as nn
from torch.nn import CrossEntropyLoss

class BERTEmbeddings(nn.Module):
    def __init__(self, config):
        super(BERTEmbeddings, self).__init__()
        """Construct the embedding module from word, position and token_type embeddings.
        """
        self.word_embeddings = nn.Embedding(config.vocab_size, config.hidden_size)
        self.position_embeddings = nn.Embedding(config.max_position_embeddings, config.hidden_size)
        self.token_type_embeddings = nn.Embedding(config.type_vocab_size, config.hidden_size)

        # self.LayerNorm is not snake-cased to stick with TensorFlow model variable name and be able to load
        # any TensorFlow checkpoint file
        self.LayerNorm = BERTLayerNorm(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)

    def forward(self, input_ids, token_type_ids=None):
        seq_length = input_ids.size(1)
        position_ids = torch.arange(seq_length, dtype=torch.long, device=input_ids.device)
        position_ids = position_ids.unsqueeze(0).expand_as(input_ids)
        if token_type_ids is None:
            token_type_ids = torch.zeros_like(input_ids)

        words_embeddings = self.word_embeddings(input_ids)
        position_embeddings = self.position_embeddings(position_ids)
        token_type_embeddings = self.token_type_embeddings(token_type_ids)

        embeddings = words_embeddings + position_embeddings + token_type_embeddings
        embeddings = self.LayerNorm(embeddings)
        embeddings = self.dropout(embeddings)
        return embeddings

As you can see, BERTEmbeddings is a class based on torch.nn.Module, but how I can convert it with keras??
Please help me to implement this.
Thank you

**Comment by anshudaur** [comment]
@whwang299 HI , I am also implementing sqlova in keras with bert embeddings.
I am using pytorch trained bert tokenizer to generate words, positions and segment embeddings .
Were you successful in implementing column attention implementation, as i still struggling with it.
Thanks
Anshu
